import { create } from 'zustand'
import type {
  VideoInfo,
  PlaylistEntry,
  PlaylistFetchResult,
  PlaylistMetadata,
  DownloadRequest,
  DownloadProgress,
  DownloadComplete,
  YtdlpFormat,
  CookieBrowser
} from '../types'
import {
  buildDownloadSucceededProperties,
  buildDownloadWorkflowProperties,
  buildFormatWorkflowProperties,
  type DownloadWorkflowProperties
} from '../telemetry/download-workflow'

export type SelectedActionKind = 'download' | 'mux' | 'convert' | 'transcode'

export interface SelectedActionSummary {
  kind: SelectedActionKind
  label: string
  hasTranscode: boolean
  hasConvert: boolean
  hasMux: boolean
}

// ── Download state tracked per item ──────────────────────────────────────────

export interface DownloadState {
  id: string
  label: string
  type: DownloadRequest['type']
  status: 'queued' | 'downloading' | 'merging' | 'transcoding' | 'complete' | 'error' | 'cancelled' | 'paused'
  percent: number
  speed: string
  eta: string
  filePath: string | null
  fileSize: number | null
  error: string | null
  tabId: string
  videoTitle: string | null
  dateAdded: number
  dateCompleted: number | null
  paused: boolean
  downloadCategory: 'video' | 'audio' | 'subtitle' | 'thumbnail' | 'extra'
  originalRequest: DownloadRequest | null
  workflow?: DownloadWorkflowProperties
}

// ── Per-tab state ────────────────────────────────────────────────────────────

export interface TabState {
  id: string
  url: string
  isLoading: boolean
  error: string | null
  videoInfo: VideoInfo | null
  playlistEntries: PlaylistEntry[] | null
  playlistMetadata: PlaylistMetadata | null
  selectedFormats: Set<string>
  selectedSubtitles: Set<string>
  selectedExtras: Set<string>
  activeTab: 'formats' | 'subtitles' | 'extras'
}

let tabCounter = 0
function createTab(): TabState {
  tabCounter++
  return {
    id: `tab-${tabCounter}`,
    url: '',
    isLoading: false,
    error: null,
    videoInfo: null,
    playlistEntries: null,
    playlistMetadata: null,
    selectedFormats: new Set<string>(),
    selectedSubtitles: new Set<string>(),
    selectedExtras: new Set<string>(),
    activeTab: 'formats'
  }
}

// ── Store shape ──────────────────────────────────────────────────────────────

export interface AppState {
  tabs: TabState[]
  closedTabs: TabState[]
  activeTabId: string

  activeView: 'video' | 'queue'

  downloads: Map<string, DownloadState>

  // Settings
  downloadDir: string
  subtitleFormat: 'original' | 'srt' | 'vtt' | 'ass'
  cookieBrowser: CookieBrowser
  preferredContainer: 'mp4' | 'mkv' | 'webm' | 'auto'
  audioConvertFormat: 'original' | 'wav' | 'flac' | 'mp3'
  videoTranscodeFormat: 'original' | 'h264-mp4' | 'prores' | 'dnxhr'
  autoIncludeAudioWithProfessionalTranscodes: boolean
  ffmpegAvailable: boolean
  hwAccel: 'cpu' | 'videotoolbox'
  analyticsEnabled: boolean
  organizeIntoFolders: boolean
  downloadAllIncludes: {
    formats: boolean
    subtitles: boolean
    thumbnails: boolean
    description: boolean
    infoJson: boolean
    comments: boolean
  }

  // Tab management
  addTab: () => string
  closeTab: (id: string) => void
  reopenClosedTab: () => void
  switchTab: (id: string) => void
  reorderTabs: (fromIndex: number, toIndex: number) => void

  // Actions (operate on active tab)
  setUrl: (url: string) => void
  fetchVideoInfo: () => Promise<void>
  fetchPlaylist: () => Promise<void>
  openPlaylistEntry: (entry: PlaylistEntry) => Promise<void>

  toggleFormat: (formatId: string) => void
  selectAllFormats: (type: 'combined' | 'video-only' | 'audio-only') => void
  deselectAllFormats: (type: 'combined' | 'video-only' | 'audio-only') => void

  toggleSubtitle: (key: string) => void
  selectAllSubtitles: (autoGenerated: boolean) => void
  deselectAllSubtitles: (autoGenerated: boolean) => void

  toggleExtra: (key: string) => void
  selectAllExtras: () => void

  startSelectedDownloads: () => Promise<void>
  downloadAll: () => Promise<void>
  cancelDownload: (id: string) => void
  updateDownloadProgress: (id: string, progress: DownloadProgress) => void
  completeDownload: (id: string, result: DownloadComplete) => void
  failDownload: (id: string, error: string) => void

  // Queue management
  setActiveView: (view: 'video' | 'queue') => void
  pauseDownload: (id: string) => void
  resumeDownload: (id: string) => Promise<void>
  retryDownload: (id: string) => Promise<void>
  pauseAll: () => void
  resumeAll: () => Promise<void>
  cancelAll: () => void
  retryFailed: () => Promise<void>
  clearCompleted: () => void

  // Settings setters
  setDownloadDir: (dir: string) => void
  setSubtitleFormat: (fmt: 'original' | 'srt' | 'vtt' | 'ass') => void
  setCookieBrowser: (browser: AppState['cookieBrowser']) => void
  setPreferredContainer: (fmt: AppState['preferredContainer']) => void
  setAudioConvertFormat: (fmt: AppState['audioConvertFormat']) => void
  setVideoTranscodeFormat: (fmt: AppState['videoTranscodeFormat']) => void
  setAutoIncludeAudioWithProfessionalTranscodes: (enabled: boolean) => void
  setFfmpegAvailable: (available: boolean) => void
  setHwAccel: (hw: AppState['hwAccel']) => void
  setAnalyticsEnabled: (enabled: boolean) => void
  setOrganizeIntoFolders: (v: boolean) => void
  setDownloadAllInclude: (key: keyof AppState['downloadAllIncludes'], value: boolean) => void
  setActiveTab: (tab: 'formats' | 'subtitles' | 'extras') => void

  reset: () => void
  restorePersistedState: (persisted: { settings: Record<string, unknown>; tabUrls: string[] }) => void

  totalSelectedCount: () => number
  selectedActionSummary: () => SelectedActionSummary
  estimatedTotalSize: () => number | null
}

// ── Helpers ──────────────────────────────────────────────────────────────────

const EXTRA_TYPES = ['description', 'info-json', 'comments'] as const
const CHAPTER_FORMATS = ['chapters:premiere-csv', 'chapters:edl', 'chapters:csv', 'chapters:txt'] as const

function buildThumbnailKeys(
  thumbnails: { id: string; resolution: string; width: number | null; height: number | null }[]
): string[] {
  const sorted = [...thumbnails].sort((a, b) => {
    const aPixels = (a.width ?? 0) * (a.height ?? 0) || parseResPixels(a.resolution)
    const bPixels = (b.width ?? 0) * (b.height ?? 0) || parseResPixels(b.resolution)
    return bPixels - aPixels
  })
  const seen = new Set<string>()
  let index = 0
  const keys: string[] = []
  for (const t of sorted) {
    const res = t.resolution || `${t.width}x${t.height}`
    if (seen.has(res) || res === 'nullxnull') continue
    seen.add(res)
    keys.push(`thumbnail:${index}`)
    index++
    if (index >= 6) break
  }
  return keys
}

function parseResPixels(res: string): number {
  const match = res.match(/(\d+)x(\d+)/)
  return match ? parseInt(match[1]) * parseInt(match[2]) : 0
}

function transcodeFormatName(fmt: string): string {
  const names: Record<string, string> = {
    'h264-mp4': 'H.264 MP4',
    'prores': 'ProRes 422',
    'dnxhr': 'DNxHR HQ'
  }
  return names[fmt] ?? fmt
}

function codecName(codec: string | null): string {
  if (!codec || codec === 'none') return ''
  if (codec.startsWith('avc1')) return 'H.264'
  if (codec.startsWith('av01')) return 'AV1'
  if (codec.startsWith('vp9') || codec.startsWith('vp09')) return 'VP9'
  if (codec.startsWith('hev') || codec.startsWith('hvc')) return 'HEVC'
  if (codec.startsWith('mp4a')) return 'AAC'
  if (codec.startsWith('opus')) return 'Opus'
  return codec.split('.')[0].toUpperCase()
}

function getFormatLabel(format: YtdlpFormat): string {
  if (format.type === 'audio-only') {
    const bitrate = format.abr ?? format.tbr
    const codec = codecName(format.acodec) || format.ext
    return bitrate ? `Audio ${Math.round(bitrate)}kbps ${codec}` : `Audio ${codec}`
  }
  const quality = format.height ? `${format.height}p` : format.resolution ?? 'unknown'
  const fps = format.fps && format.fps > 30 ? `${format.fps}fps` : ''
  const codec = codecName(format.vcodec) || format.ext
  return `${quality}${fps} ${codec}`.trim()
}

function isProfessionalTranscodeFormat(fmt: AppState['videoTranscodeFormat']): boolean {
  return fmt === 'prores' || fmt === 'dnxhr'
}

function selectedFormatNeedsTranscode(
  format: YtdlpFormat,
  preferredContainer: AppState['preferredContainer'],
  videoTranscodeFormat: AppState['videoTranscodeFormat']
): boolean {
  if (format.type === 'video-only') return videoTranscodeFormat !== 'original'
  if (format.type === 'audio-only') return false
  if (preferredContainer !== 'mp4') return false
  const codec = (format.vcodec ?? '').toLowerCase()
  return codec.startsWith('vp9') || codec.startsWith('av01') || codec.startsWith('av1')
}

function selectedFormatNeedsConvert(
  format: YtdlpFormat,
  audioConvertFormat: AppState['audioConvertFormat']
): boolean {
  return format.type === 'audio-only' && audioConvertFormat !== 'original'
}

function selectedFormatNeedsMux(format: YtdlpFormat): boolean {
  return format.type === 'video-only'
}

function selectedMergePresetActionKind(
  formatId: string,
  videoInfo: VideoInfo,
  preferredContainer: AppState['preferredContainer']
): SelectedActionKind {
  const resMatch = formatId.match(/height<=(\d+)/)
  const maxHeight = resMatch ? parseInt(resMatch[1]) : null
  const bestVideo = videoInfo.formats
    .filter((format) =>
      format.type === 'video-only' &&
      (maxHeight == null || (format.height ?? 0) <= maxHeight)
    )
    .sort((a, b) => (b.height ?? 0) - (a.height ?? 0) || (b.tbr ?? 0) - (a.tbr ?? 0))[0]

  const codec = (bestVideo?.vcodec ?? '').toLowerCase()
  const bestVideoNeedsMp4Transcode =
    preferredContainer === 'mp4' &&
    (codec.startsWith('vp9') || codec.startsWith('vp09') || codec.startsWith('av01') || codec.startsWith('av1'))

  return bestVideoNeedsMp4Transcode ? 'transcode' : 'mux'
}

function subtitleKeyParts(key: string): { lang: string; ext: string } {
  const idx = key.lastIndexOf(':')
  return idx === -1
    ? { lang: key, ext: '' }
    : { lang: key.slice(0, idx), ext: key.slice(idx + 1) }
}

function formatSubtitleSourcePreference(sourceFormats: Set<string>): string {
  const formats = [...sourceFormats].filter(Boolean)
  return formats.length === 1 ? `${formats[0]}/best` : 'best'
}

function formatSubtitleOutputLabel(
  subtitleFormat: AppState['subtitleFormat'],
  sourceFormats: Set<string>
): string {
  if (subtitleFormat !== 'original') return subtitleFormat.toUpperCase()
  const formats = [...sourceFormats].filter(Boolean)
  return formats.length === 1 ? formats[0].toUpperCase() : 'Original'
}

function buildSubtitleKeys(
  tracks: Record<string, import('../types').SubtitleTrack[]>,
  autoGenerated: boolean
): string[] {
  const keys: string[] = []
  for (const [lang, entries] of Object.entries(tracks)) {
    for (const track of entries) {
      if (track.isAutoGenerated === autoGenerated) {
        keys.push(`${lang}:${track.ext}`)
      }
    }
  }
  return keys
}

function sanitizeTitle(title: string): string {
  return title.replace(/[<>:"/\\|?*]/g, '_').replace(/\.+$/, '').slice(0, 200).trim() || 'untitled'
}

function getCategoryFolder(category: DownloadState['downloadCategory']): string {
  const map: Record<string, string> = {
    video: 'video',
    audio: 'audio',
    subtitle: 'subtitles',
    thumbnail: 'thumbnails',
    extra: 'extras'
  }
  return map[category] ?? ''
}

function computeOutputDir(
  baseDir: string,
  videoTitle: string,
  category: DownloadState['downloadCategory'],
  organize: boolean
): string {
  if (!organize) return baseDir
  const safeName = sanitizeTitle(videoTitle)
  const folder = getCategoryFolder(category)
  return folder ? `${baseDir}/${safeName}/${folder}` : `${baseDir}/${safeName}`
}

function cleanErrorMessage(err: unknown): string {
  const msg = err instanceof Error ? err.message : String(err)
  const cleaned = msg.replace(/^Error invoking remote method '[^']+': Error: /, '')
  const cookieBrowserMatch = cleaned.match(/could not find ([a-z]+) cookies database/i)
  if (cookieBrowserMatch) {
    const browser = cookieBrowserMatch[1].charAt(0).toUpperCase() + cookieBrowserMatch[1].slice(1)
    return `${browser} sign-in is selected, but Pullframe could not find ${browser}'s YouTube cookies. In Settings, set YouTube sign-in to Off, or sign into YouTube in ${browser} and fully quit ${browser} before trying again.`
  }

  if (/could not copy.*cookies database|database is locked|browser.*closed/i.test(cleaned)) {
    return 'Pullframe could not read your browser sign-in cookies. Fully quit the selected browser before downloading, or set YouTube sign-in to Off in Settings.'
  }

  if (/operation not permitted|permission denied|not authorized/i.test(cleaned) && /safari|cookies/i.test(cleaned)) {
    return 'macOS blocked Safari sign-in access. Open Full Disk Access in Settings, allow Pullframe, then restart Pullframe.'
  }

  if (/requested format is not available/i.test(cleaned)) {
    return 'This video could not be loaded with the selected browser sign-in. Set YouTube sign-in to Off or choose another browser in Settings, then try again.'
  }

  return cleaned
}

function isBrowserSignInUnavailableError(err: unknown): boolean {
  const msg = err instanceof Error ? err.message : String(err)
  return /could not find [a-z]+ cookies database|could not copy.*cookies database|database is locked|browser.*closed|operation not permitted|permission denied|not authorized|requested format is not available/i.test(msg)
}

async function withBrowserSignInFallback<T>(
  cookieBrowser: AppState['cookieBrowser'],
  run: (browser: AppState['cookieBrowser']) => Promise<T>
): Promise<{ result: T; usedFallback: boolean }> {
  try {
    return { result: await run(cookieBrowser), usedFallback: false }
  } catch (err) {
    if (cookieBrowser === 'none' || !isBrowserSignInUnavailableError(err)) {
      throw err
    }
    return { result: await run('none'), usedFallback: true }
  }
}

function normalizePlaylistFetchResult(value: PlaylistEntry[] | PlaylistFetchResult): PlaylistFetchResult {
  return Array.isArray(value)
    ? {
        entries: value,
        metadata: {
          title: null,
          channelName: null,
          playlistName: null,
          count: value.length
        }
      }
    : value
}

function getPlaylistEntryUrl(entry: PlaylistEntry): string {
  return entry.url.startsWith('http')
    ? entry.url
    : `https://www.youtube.com/watch?v=${entry.id}`
}

function findExistingVideoTabId(tabs: TabState[], entryId: string, targetUrl: string): string | null {
  const normalizedTarget = normalizeYouTubeVideoUrl(targetUrl, entryId)
  return tabs.find((tab) => {
    if (tab.videoInfo?.id === entryId) return true
    return normalizeYouTubeVideoUrl(tab.url, entryId) === normalizedTarget
  })?.id ?? null
}

function normalizeYouTubeVideoUrl(url: string, fallbackId?: string): string {
  try {
    const parsed = new URL(url)
    const videoId = parsed.searchParams.get('v') ?? (
      parsed.hostname.includes('youtu.be')
        ? parsed.pathname.replace(/^\//, '').split('/')[0]
        : null
    ) ?? fallbackId
    return videoId ? `youtube:${videoId}` : url.trim()
  } catch {
    return fallbackId ? `youtube:${fallbackId}` : url.trim()
  }
}

function _getActiveTab(state: { tabs: TabState[]; activeTabId: string }): TabState | undefined {
  return state.tabs.find((t) => t.id === state.activeTabId)
}

function updateActiveTab(
  state: { tabs: TabState[]; activeTabId: string },
  updater: (tab: TabState) => Partial<TabState>
): { tabs: TabState[] } {
  return {
    tabs: state.tabs.map((t) =>
      t.id === state.activeTabId ? { ...t, ...updater(t) } : t
    )
  }
}

// ── Initial state ────────────────────────────────────────────────────────────

const firstTab = createTab()

const initialState = {
  tabs: [firstTab] as TabState[],
  closedTabs: [] as TabState[],
  activeTabId: firstTab.id,
  activeView: 'video' as const,
  downloads: new Map<string, DownloadState>(),
  downloadDir: '',
  subtitleFormat: 'original' as const,
  cookieBrowser: 'none' as const,
  preferredContainer: 'mp4' as const,
  audioConvertFormat: 'original' as const,
  videoTranscodeFormat: 'original' as const,
  autoIncludeAudioWithProfessionalTranscodes: true,
  ffmpegAvailable: false,
  hwAccel: 'cpu' as const,
  analyticsEnabled: true,
  organizeIntoFolders: true,
  downloadAllIncludes: {
    formats: true,
    subtitles: true,
    thumbnails: true,
    description: true,
    infoJson: false,
    comments: false
  }
}

// ── Store ────────────────────────────────────────────────────────────────────

export const useAppStore = create<AppState>((set, get) => ({
  ...initialState,

  addTab: () => {
    const newTab = createTab()
    set((state) => ({
      tabs: [...state.tabs, newTab],
      activeTabId: newTab.id
    }))
    return newTab.id
  },

  closeTab: (id) => {
    set((state) => {
      if (state.tabs.length <= 1) return state
      const closedTab = state.tabs.find((t) => t.id === id)
      const newTabs = state.tabs.filter((t) => t.id !== id)
      let newActiveId = state.activeTabId
      if (state.activeTabId === id) {
        const closedIndex = state.tabs.findIndex((t) => t.id === id)
        const newIndex = Math.min(closedIndex, newTabs.length - 1)
        newActiveId = newTabs[newIndex].id
      }
      return {
        tabs: newTabs,
        activeTabId: newActiveId,
        closedTabs: closedTab ? [...state.closedTabs, closedTab].slice(-10) : state.closedTabs
      }
    })
  },

  reopenClosedTab: () => {
    set((state) => {
      const reopenedTab = state.closedTabs.at(-1)
      if (!reopenedTab) return state
      return {
        tabs: [...state.tabs, reopenedTab],
        closedTabs: state.closedTabs.slice(0, -1),
        activeTabId: reopenedTab.id,
        activeView: 'video'
      }
    })
  },

  switchTab: (id) => set({ activeTabId: id }),

  reorderTabs: (fromIndex, toIndex) => {
    set((state) => {
      const newTabs = [...state.tabs]
      const [moved] = newTabs.splice(fromIndex, 1)
      newTabs.splice(toIndex, 0, moved)
      return { tabs: newTabs }
    })
  },

  setUrl: (url) => set((state) => updateActiveTab(state, () => ({ url }))),

  fetchVideoInfo: async () => {
    const state = get()
    const tab = _getActiveTab(state)
    if (!tab || !tab.url.trim()) return

    const tabId = tab.id
    const url = tab.url.trim()

    set((s) =>
      updateActiveTab(s, () => ({
        isLoading: true,
        error: null,
        videoInfo: null,
        playlistEntries: null,
        playlistMetadata: null
      }))
    )

    const isPlaylist = (() => {
      try {
        const parsed = new URL(url)
        if (parsed.searchParams.has('list')) return true
        if (parsed.pathname.includes('/playlist')) return true
        if (parsed.pathname.startsWith('/@') || parsed.pathname.includes('/channel/') || parsed.pathname.includes('/c/')) return true
        return false
      } catch { return false }
    })()

    try {
      if (isPlaylist) {
        const { result, usedFallback } = await withBrowserSignInFallback(get().cookieBrowser, (browser) =>
          window.api.fetchPlaylist(url, browser)
        )
        if (usedFallback) set({ cookieBrowser: 'none' })
        const playlist = normalizePlaylistFetchResult(result)
        set((s) => ({
          tabs: s.tabs.map((t) =>
            t.id === tabId
              ? { ...t, playlistEntries: playlist.entries, playlistMetadata: playlist.metadata, isLoading: false }
              : t
          )
        }))
      } else {
        const { result: info, usedFallback } = await withBrowserSignInFallback(get().cookieBrowser, (browser) =>
          window.api.fetchVideoInfo(url, browser)
        )
        if (usedFallback) set({ cookieBrowser: 'none' })
        set((s) => ({
          tabs: s.tabs.map((t) =>
            t.id === tabId
              ? {
                  ...t,
                  videoInfo: info,
                  isLoading: false,
                  selectedFormats: new Set<string>(),
                  selectedSubtitles: new Set<string>(),
                  selectedExtras: new Set<string>()
                }
              : t
          )
        }))
      }
    } catch (err) {
      set((s) => ({
        tabs: s.tabs.map((t) =>
          t.id === tabId
            ? { ...t, error: cleanErrorMessage(err), isLoading: false }
            : t
        )
      }))
    }
  },

  fetchPlaylist: async () => {
    const state = get()
    const tab = _getActiveTab(state)
    if (!tab || !tab.url.trim()) return

    const tabId = tab.id

    set((s) =>
      updateActiveTab(s, () => ({
        isLoading: true,
        error: null,
        playlistEntries: null,
        playlistMetadata: null
      }))
    )

    try {
      const { result, usedFallback } = await withBrowserSignInFallback(get().cookieBrowser, (browser) =>
        window.api.fetchPlaylist(tab.url, browser)
      )
      if (usedFallback) set({ cookieBrowser: 'none' })
      const playlist = normalizePlaylistFetchResult(result)
      set((s) => ({
        tabs: s.tabs.map((t) =>
          t.id === tabId
            ? { ...t, playlistEntries: playlist.entries, playlistMetadata: playlist.metadata, isLoading: false }
            : t
        )
      }))
    } catch (err) {
      set((s) => ({
        tabs: s.tabs.map((t) =>
          t.id === tabId
            ? { ...t, error: cleanErrorMessage(err), isLoading: false }
            : t
        )
      }))
    }
  },

  openPlaylistEntry: async (entry) => {
    const targetUrl = getPlaylistEntryUrl(entry)
    const existingTabId = findExistingVideoTabId(get().tabs, entry.id, targetUrl)

    if (existingTabId) {
      set({ activeTabId: existingTabId, activeView: 'video' })
      return
    }

    const newTabId = get().addTab()
    set({ activeTabId: newTabId, activeView: 'video' })
    get().setUrl(targetUrl)
    await get().fetchVideoInfo()
  },

  toggleFormat: (formatId) =>
    set((state) => {
      const tab = _getActiveTab(state)
      if (!tab) return state
      const next = new Set(tab.selectedFormats)
      if (next.has(formatId)) {
        next.delete(formatId)
      } else {
        next.add(formatId)

        const isMergePreset = formatId.startsWith('bestvideo[')
        if (isMergePreset && tab.videoInfo) {
          const resMatch = formatId.match(/height<=(\d+)/)
          if (resMatch) {
            const res = parseInt(resMatch[1])
            for (const f of tab.videoInfo.formats) {
              if (f.type === 'video-only' && f.height === res) {
                next.delete(f.formatId)
              }
            }
          }
        } else if (!isMergePreset && tab.videoInfo) {
          const format = tab.videoInfo.formats.find((f) => f.formatId === formatId)
          if (format?.type === 'video-only' && format.height) {
            const mergeKey = `bestvideo[height<=${format.height}]+bestaudio/best`
            next.delete(mergeKey)
          }
        }
      }
      return updateActiveTab(state, () => ({ selectedFormats: next }))
    }),

  selectAllFormats: (type) =>
    set((state) => {
      const tab = _getActiveTab(state)
      if (!tab?.videoInfo) return state
      const next = new Set(tab.selectedFormats)
      for (const f of tab.videoInfo.formats) {
        if (f.type === type) next.add(f.formatId)
      }
      return updateActiveTab(state, () => ({ selectedFormats: next }))
    }),

  deselectAllFormats: (type) =>
    set((state) => {
      const tab = _getActiveTab(state)
      if (!tab?.videoInfo) return state
      const idsToRemove = new Set(
        tab.videoInfo.formats.filter((f) => f.type === type).map((f) => f.formatId)
      )
      const next = new Set(tab.selectedFormats)
      for (const id of idsToRemove) {
        next.delete(id)
      }
      return updateActiveTab(state, () => ({ selectedFormats: next }))
    }),

  toggleSubtitle: (key) =>
    set((state) => {
      const tab = _getActiveTab(state)
      if (!tab) return state
      const next = new Set(tab.selectedSubtitles)
      if (next.has(key)) next.delete(key)
      else next.add(key)
      return updateActiveTab(state, () => ({ selectedSubtitles: next }))
    }),

  selectAllSubtitles: (autoGenerated) =>
    set((state) => {
      const tab = _getActiveTab(state)
      if (!tab?.videoInfo) return state
      const source = autoGenerated ? tab.videoInfo.automaticCaptions : tab.videoInfo.subtitles
      const keys = buildSubtitleKeys(source, autoGenerated)
      const next = new Set(tab.selectedSubtitles)
      for (const k of keys) next.add(k)
      return updateActiveTab(state, () => ({ selectedSubtitles: next }))
    }),

  deselectAllSubtitles: (autoGenerated) =>
    set((state) => {
      const tab = _getActiveTab(state)
      if (!tab?.videoInfo) return state
      const source = autoGenerated ? tab.videoInfo.automaticCaptions : tab.videoInfo.subtitles
      const keysToRemove = new Set(buildSubtitleKeys(source, autoGenerated))
      const next = new Set(tab.selectedSubtitles)
      for (const k of keysToRemove) next.delete(k)
      return updateActiveTab(state, () => ({ selectedSubtitles: next }))
    }),

  toggleExtra: (key) =>
    set((state) => {
      const tab = _getActiveTab(state)
      if (!tab) return state
      const next = new Set(tab.selectedExtras)
      if (next.has(key)) next.delete(key)
      else next.add(key)
      return updateActiveTab(state, () => ({ selectedExtras: next }))
    }),

  selectAllExtras: () =>
    set((state) => {
      const tab = _getActiveTab(state)
      if (!tab) return state
      const extras = new Set<string>(EXTRA_TYPES)
      if (tab.videoInfo) {
        for (const k of buildThumbnailKeys(tab.videoInfo.thumbnails)) {
          extras.add(k)
        }
        if (tab.videoInfo.chapters.length > 0) {
          for (const k of CHAPTER_FORMATS) {
            extras.add(k)
          }
        }
      }
      return updateActiveTab(state, () => ({ selectedExtras: extras }))
    }),

  startSelectedDownloads: async () => {
    const state = get()
    const tab = _getActiveTab(state)
    if (!tab?.videoInfo) return

    const {
      downloadDir,
      subtitleFormat,
      cookieBrowser,
      preferredContainer,
      audioConvertFormat,
      organizeIntoFolders,
      videoTranscodeFormat,
      autoIncludeAudioWithProfessionalTranscodes
    } = state
    const videoInfo = tab.videoInfo
    const url = tab.url
    const tabId = tab.id
    const videoTitle = videoInfo.title
    const now = Date.now()

    const requests: DownloadRequest[] = []
    const newDownloads = new Map(state.downloads)

    const mkDownload = (
      opts: Pick<DownloadState, 'id' | 'label' | 'type' | 'fileSize' | 'downloadCategory'> & {
        originalRequest: DownloadRequest | null
        status?: DownloadState['status']
        workflow?: DownloadWorkflowProperties
      }
    ): DownloadState => ({
      id: opts.id,
      label: opts.label,
      type: opts.type,
      status: opts.status ?? 'queued',
      percent: 0,
      speed: '',
      eta: '',
      filePath: null,
      fileSize: opts.fileSize,
      error: null,
      tabId,
      videoTitle,
      dateAdded: now,
      dateCompleted: null,
      paused: false,
      downloadCategory: opts.downloadCategory,
      originalRequest: opts.originalRequest,
      workflow: opts.workflow
    })

    // Format downloads
    for (const formatId of tab.selectedFormats) {
      const isMergePreset = formatId.startsWith('bestvideo[')

      if (isMergePreset) {
        const id = `${tabId}-format-${formatId}-${now}`
        const resMatch = formatId.match(/height<=(\d+)/)
        const res = resMatch ? parseInt(resMatch[1]) : null
        const resLabel = res ? (res >= 2160 ? `4K ${res}p` : `${res}p`) : 'Best quality'
        const label = resMatch ? `${resLabel} + audio (merged)` : 'Best quality merged'
        const outputDir = computeOutputDir(downloadDir, videoTitle, 'video', organizeIntoFolders)
        const request: DownloadRequest = {
          id, url, type: 'format', formatId,
          outputDir, cookieBrowser, preferredContainer,
          videoDuration: videoInfo.duration,
          hwAccel: state.hwAccel !== 'cpu' ? state.hwAccel : undefined,
          videoTitle
        }
        let estimatedSize: number | null = null
        if (resMatch) {
          const r = parseInt(resMatch[1])
          const bestVideo = videoInfo.formats
            .filter((f) => f.type === 'video-only' && (f.height ?? 0) <= r)
            .sort((a, b) => (b.height ?? 0) - (a.height ?? 0))[0]
          const bestAudio = videoInfo.formats
            .filter((f) => f.type === 'audio-only')
            .sort((a, b) => (b.abr ?? b.tbr ?? 0) - (a.abr ?? a.tbr ?? 0))[0]
          const videoSize = bestVideo?.filesize ?? bestVideo?.filesizeApprox ?? null
          const audioSize = bestAudio?.filesize ?? bestAudio?.filesizeApprox ?? null
          if (videoSize && audioSize) estimatedSize = videoSize + audioSize
          else if (videoSize) estimatedSize = videoSize
        }

        requests.push(request)
        newDownloads.set(id, mkDownload({
          id, label, type: 'format', fileSize: estimatedSize,
          downloadCategory: 'video',
          originalRequest: request,
          workflow: buildDownloadWorkflowProperties({
            downloadCategory: 'video',
            type: 'format',
            originalRequest: request
          })
        }))
        continue
      }

      const format = videoInfo.formats.find((f) => f.formatId === formatId)
      if (!format) continue

      const id = `${tabId}-format-${formatId}-${now}`
      const category: DownloadState['downloadCategory'] = format.type === 'audio-only' ? 'audio' : 'video'
      const outputDir = computeOutputDir(downloadDir, videoTitle, category, organizeIntoFolders)
      const shouldMergeBestAudio =
        format.type === 'video-only' &&
        isProfessionalTranscodeFormat(videoTranscodeFormat) &&
        autoIncludeAudioWithProfessionalTranscodes
      const requestFormatId = shouldMergeBestAudio ? `${formatId}+bestaudio/best` : formatId
      const request: DownloadRequest = {
        id, url, type: 'format', formatId: requestFormatId,
        outputDir, cookieBrowser, preferredContainer,
        videoDuration: videoInfo.duration,
        videoTitle,
        ...(shouldMergeBestAudio ? { includeBestAudio: true } : {}),
        ...(format.type === 'video-only' && videoTranscodeFormat !== 'original'
          ? { videoTranscodeTo: videoTranscodeFormat }
          : {}),
        ...(format.type === 'audio-only' && audioConvertFormat !== 'original'
          ? { audioConvertTo: audioConvertFormat }
          : {})
      }
      requests.push(request)

      newDownloads.set(id, mkDownload({
        id,
        label: format.type === 'video-only' && videoTranscodeFormat !== 'original'
          ? `${getFormatLabel(format)} → ${transcodeFormatName(videoTranscodeFormat)}${shouldMergeBestAudio ? ' + PCM audio' : ''}`
          : getFormatLabel(format),
        type: 'format',
        fileSize: format.filesize ?? format.filesizeApprox ?? null,
        downloadCategory: category,
        originalRequest: request,
        workflow: buildFormatWorkflowProperties(format.type, request)
      }))
    }

    // Subtitle downloads (batched by manual/auto)
    const manualLangs: string[] = []
    const autoLangs: string[] = []
    const manualSourceFormats = new Set<string>()
    const autoSourceFormats = new Set<string>()
    const subLangNames: string[] = []
    for (const key of tab.selectedSubtitles) {
      const { lang, ext } = subtitleKeyParts(key)
      const isAuto = !!(videoInfo.automaticCaptions[lang]?.some(
        (t) => t.ext === ext && t.isAutoGenerated
      ))
      const source = isAuto ? videoInfo.automaticCaptions : videoInfo.subtitles
      const track = source[lang]?.[0]
      const langName = track?.languageName || lang.toUpperCase()
      if (isAuto) {
        autoLangs.push(lang)
        autoSourceFormats.add(ext)
      } else {
        manualLangs.push(lang)
        manualSourceFormats.add(ext)
      }
      subLangNames.push(langName)
    }

    const subOutputDir = computeOutputDir(downloadDir, videoTitle, 'subtitle', organizeIntoFolders)

    if (manualLangs.length > 0) {
      const id = `${tabId}-sub-manual`
      const request: DownloadRequest = {
        id, url, type: 'subtitle',
        subtitleLang: manualLangs.join(','),
        subtitleSourceFormat: formatSubtitleSourcePreference(manualSourceFormats),
        subtitleFormat,
        outputDir: subOutputDir, cookieBrowser
      }
      requests.push(request)
      const outputLabel = formatSubtitleOutputLabel(subtitleFormat, manualSourceFormats)
      const label = manualLangs.length === 1
        ? `${subLangNames[0]} (${outputLabel})`
        : `${manualLangs.length} subtitles (${outputLabel})`
      newDownloads.set(id, mkDownload({
        id, label, type: 'subtitle',
        fileSize: null,
        downloadCategory: 'subtitle',
        originalRequest: request,
        workflow: buildDownloadWorkflowProperties({
          downloadCategory: 'subtitle',
          type: 'subtitle',
          originalRequest: request
        })
      }))
    }

    if (autoLangs.length > 0) {
      const id = `${tabId}-sub-auto`
      const request: DownloadRequest = {
        id, url, type: 'auto-subtitle',
        subtitleLang: autoLangs.join(','),
        subtitleSourceFormat: formatSubtitleSourcePreference(autoSourceFormats),
        subtitleFormat,
        outputDir: subOutputDir, cookieBrowser
      }
      requests.push(request)
      const outputLabel = formatSubtitleOutputLabel(subtitleFormat, autoSourceFormats)
      const label = autoLangs.length === 1
        ? `${autoLangs[0].toUpperCase()} (${outputLabel}) [auto]`
        : `${autoLangs.length} auto subtitles (${outputLabel})`
      newDownloads.set(id, mkDownload({
        id, label, type: 'auto-subtitle',
        fileSize: null,
        downloadCategory: 'subtitle',
        originalRequest: request,
        workflow: buildDownloadWorkflowProperties({
          downloadCategory: 'subtitle',
          type: 'auto-subtitle',
          originalRequest: request
        })
      }))
    }

    // Thumbnail downloads (direct URL)
    const sortedThumbs = [...videoInfo.thumbnails].sort((a, b) => {
      const aP = (a.width ?? 0) * (a.height ?? 0) || (() => { const m = a.resolution.match(/(\d+)x(\d+)/); return m ? parseInt(m[1]) * parseInt(m[2]) : 0 })()
      const bP = (b.width ?? 0) * (b.height ?? 0) || (() => { const m = b.resolution.match(/(\d+)x(\d+)/); return m ? parseInt(m[1]) * parseInt(m[2]) : 0 })()
      return bP - aP
    })
    const thumbSeen = new Set<string>()
    const dedupedThumbs = sortedThumbs.filter((t) => {
      const key = t.resolution || `${t.width}x${t.height}`
      if (thumbSeen.has(key) || key === 'nullxnull') return false
      thumbSeen.add(key)
      return true
    }).slice(0, 6)

    const thumbnailDownloads: { thumbUrl: string; resolution: string; id: string; outputDir: string; filename: string }[] = []
    for (const key of tab.selectedExtras) {
      if (!key.startsWith('thumbnail:')) continue
      const index = parseInt(key.replace('thumbnail:', ''))
      const thumb = dedupedThumbs[index]
      if (!thumb) continue

      const id = `${tabId}-thumb-${thumb.resolution}`
      const thumbOutputDir = computeOutputDir(downloadDir, videoTitle, 'thumbnail', organizeIntoFolders)
      const safeTitle = videoTitle.replace(/[<>:"/\\|?*]/g, '_').slice(0, 100)
      const ext = thumb.url.includes('.webp') ? 'webp' : thumb.url.includes('.png') ? 'png' : 'jpg'
      const filename = `${safeTitle}_${thumb.resolution}.${ext}`

      thumbnailDownloads.push({ thumbUrl: thumb.url, resolution: thumb.resolution, id, outputDir: thumbOutputDir, filename })
      newDownloads.set(id, mkDownload({
        id, label: `Thumbnail ${thumb.resolution}`, type: 'thumbnail',
        fileSize: null,
        downloadCategory: 'thumbnail',
        originalRequest: null,
        workflow: buildDownloadWorkflowProperties({
          downloadCategory: 'thumbnail',
          type: 'thumbnail',
          originalRequest: null
        })
      }))
    }

    // Extras + chapter exports
    const chapterExports: string[] = []
    for (const extra of tab.selectedExtras) {
      if (extra.startsWith('thumbnail:')) continue
      if (extra.startsWith('chapters:')) {
        chapterExports.push(extra)
        continue
      }

      const id = `${tabId}-extra-${extra}`
      const outputDir = computeOutputDir(downloadDir, videoTitle, 'extra', organizeIntoFolders)
      const request: DownloadRequest = {
        id, url, type: extra as DownloadRequest['type'], outputDir, cookieBrowser
      }
      requests.push(request)
      newDownloads.set(id, mkDownload({
        id, label: extra.replace('-', ' '), type: request.type,
        fileSize: null,
        downloadCategory: 'extra',
        originalRequest: request,
        workflow: buildDownloadWorkflowProperties({
          downloadCategory: 'extra',
          type: request.type,
          originalRequest: request
        })
      }))
    }

    const chapterFormatLabels: Record<string, string> = {
      'chapters:premiere-csv': 'Chapters (Premiere CSV)',
      'chapters:edl': 'Chapters (EDL)',
      'chapters:csv': 'Chapters (CSV)',
      'chapters:txt': 'Chapters (YouTube TXT)'
    }
    const chapterOutputDir = computeOutputDir(downloadDir, videoTitle, 'extra', organizeIntoFolders)
    for (const chKey of chapterExports) {
      const id = `${tabId}-extra-${chKey}`
      newDownloads.set(id, mkDownload({
        id, label: chapterFormatLabels[chKey] ?? chKey, type: 'description',
        fileSize: null,
        downloadCategory: 'extra',
        originalRequest: null,
        workflow: buildDownloadWorkflowProperties({
          downloadCategory: 'extra',
          type: 'description',
          originalRequest: null
        })
      }))
    }

    set((s) => ({
      downloads: newDownloads,
      ...updateActiveTab(s, () => ({
        selectedFormats: new Set<string>(),
        selectedSubtitles: new Set<string>(),
        selectedExtras: new Set<string>()
      }))
    }))

    // Thumbnail downloads
    for (const td of thumbnailDownloads) {
      window.api.downloadThumbnail({
        url: td.thumbUrl,
        outputDir: td.outputDir,
        filename: td.filename
      }).then((result) => {
        let completedDownload: DownloadState | null = null
        set((s) => {
          const updated = new Map(s.downloads)
          const existing = updated.get(td.id)
          if (existing) {
            completedDownload = { ...existing, status: 'complete', percent: 100, filePath: result.filePath, fileSize: result.fileSize, dateCompleted: Date.now() }
            updated.set(td.id, completedDownload)
          }
          return { downloads: updated }
        })
        if (completedDownload) {
          window.api.trackEvent({
            eventType: 'download.succeeded',
            properties: buildDownloadSucceededProperties(completedDownload)
          }).catch(() => {})
        }
      }).catch((err) => {
        set((s) => {
          const updated = new Map(s.downloads)
          const existing = updated.get(td.id)
          if (existing) {
            updated.set(td.id, { ...existing, status: 'error', error: cleanErrorMessage(err) })
          }
          return { downloads: updated }
        })
      })
    }

    // yt-dlp downloads
    for (const request of requests) {
      window.api.startDownload(request).catch((err) => {
        const errorMsg = cleanErrorMessage(err)
        set((s) => {
          const updated = new Map(s.downloads)
          const existing = updated.get(request.id)
          if (existing) {
            updated.set(request.id, { ...existing, status: 'error', error: errorMsg })
          }
          return { downloads: updated }
        })
      })
    }

    // Chapter exports
    for (const chKey of chapterExports) {
      const id = `${tabId}-extra-${chKey}`
      const format = chKey.replace('chapters:', '') as 'premiere-csv' | 'edl' | 'csv' | 'txt'
      try {
        const result = await window.api.exportChapters({
          chapters: videoInfo.chapters,
          title: videoInfo.title,
          format,
          outputDir: chapterOutputDir
        })
        let completedDownload: DownloadState | null = null
        set((s) => {
          const updated = new Map(s.downloads)
          const existing = updated.get(id)
          if (existing) {
            completedDownload = {
              ...existing,
              status: 'complete', percent: 100,
              filePath: result.filePath, fileSize: result.fileSize,
              dateCompleted: Date.now()
            }
            updated.set(id, completedDownload)
          }
          return { downloads: updated }
        })
        if (completedDownload) {
          window.api.trackEvent({
            eventType: 'download.succeeded',
            properties: buildDownloadSucceededProperties(completedDownload)
          }).catch(() => {})
        }
      } catch (err) {
        const errorMsg = cleanErrorMessage(err)
        set((s) => {
          const updated = new Map(s.downloads)
          const existing = updated.get(id)
          if (existing) {
            updated.set(id, { ...existing, status: 'error', error: errorMsg })
          }
          return { downloads: updated }
        })
      }
    }
  },

  downloadAll: async () => {
    const state = get()
    const tab = _getActiveTab(state)
    if (!tab?.videoInfo) return

    const info = tab.videoInfo

    const allFormats = new Set(info.formats.map((f) => f.formatId))

    const allSubtitles = new Set<string>()
    for (const [lang, tracks] of Object.entries(info.subtitles)) {
      for (const track of tracks) allSubtitles.add(`${lang}:${track.ext}`)
    }
    for (const [lang, tracks] of Object.entries(info.automaticCaptions)) {
      for (const track of tracks) allSubtitles.add(`${lang}:${track.ext}`)
    }

    const allExtras = new Set<string>(EXTRA_TYPES)
    for (const k of buildThumbnailKeys(info.thumbnails)) {
      allExtras.add(k)
    }
    if (info.chapters.length > 0) {
      for (const k of CHAPTER_FORMATS) {
        allExtras.add(k)
      }
    }

    set((s) =>
      updateActiveTab(s, () => ({
        selectedFormats: allFormats,
        selectedSubtitles: allSubtitles,
        selectedExtras: allExtras
      }))
    )

    await get().startSelectedDownloads()
  },

  cancelDownload: (id) => {
    window.api.cancelDownload(id)
    set((s) => {
      const updated = new Map(s.downloads)
      const existing = updated.get(id)
      if (existing) {
        updated.set(id, { ...existing, status: 'cancelled' })
      }
      return { downloads: updated }
    })
  },

  updateDownloadProgress: (id, progress) =>
    set((state) => {
      const updated = new Map(state.downloads)
      const existing = updated.get(id)
      if (!existing) return state
      if (existing.status === 'paused' || existing.status === 'cancelled') return state

      const status =
        progress.stage === 'merging'
          ? 'merging'
          : progress.stage === 'postprocessing'
            ? 'transcoding'
            : progress.stage === 'complete'
              ? 'complete'
              : progress.stage === 'error'
                ? 'error'
                : 'downloading'

      updated.set(id, {
        ...existing,
        status,
        percent: progress.percent,
        speed: progress.speed,
        eta: progress.eta
      })
      return { downloads: updated }
    }),

  completeDownload: (id, result) => {
    set((s) => {
      const updated = new Map(s.downloads)
      const d = updated.get(id)
      if (!d) return s

      updated.set(id, {
        ...d,
        status: 'complete',
        percent: 100,
        filePath: result.filePath,
        fileSize: result.fileSize,
        speed: '',
        eta: '',
        dateCompleted: Date.now()
      })
      return { downloads: updated }
    })
  },

  failDownload: (id, error) =>
    set((state) => {
      const updated = new Map(state.downloads)
      const existing = updated.get(id)
      if (!existing) return state
      if (existing.status === 'paused' || existing.status === 'cancelled') return state

      updated.set(id, {
        ...existing,
        status: 'error',
        error,
        speed: '',
        eta: ''
      })
      return { downloads: updated }
    }),

  setActiveView: (view) => set({ activeView: view }),

  pauseDownload: (id) => {
    window.api.cancelDownload(id)
    set((state) => {
      const updated = new Map(state.downloads)
      const existing = updated.get(id)
      if (existing && (existing.status === 'downloading' || existing.status === 'queued' || existing.status === 'merging' || existing.status === 'transcoding')) {
        updated.set(id, { ...existing, status: 'paused', paused: true, speed: '', eta: '' })
      }
      return { downloads: updated }
    })
  },

  resumeDownload: async (id) => {
    const state = get()
    const download = state.downloads.get(id)
    if (!download?.originalRequest || !download.paused) return

    set((s) => {
      const updated = new Map(s.downloads)
      const existing = updated.get(id)
      if (existing) {
        updated.set(id, { ...existing, status: 'queued', paused: false, percent: 0, error: null, speed: '', eta: '' })
      }
      return { downloads: updated }
    })

    window.api.startDownload(download.originalRequest).catch((err) => {
      const errorMsg = cleanErrorMessage(err)
      set((s) => {
        const updated = new Map(s.downloads)
        const existing = updated.get(id)
        if (existing) {
          updated.set(id, { ...existing, status: 'error', error: errorMsg })
        }
        return { downloads: updated }
      })
    })
  },

  retryDownload: async (id) => {
    const state = get()
    const download = state.downloads.get(id)
    if (!download?.originalRequest) return

    set((s) => {
      const updated = new Map(s.downloads)
      const existing = updated.get(id)
      if (existing) {
        updated.set(id, { ...existing, status: 'queued', percent: 0, error: null, speed: '', eta: '', paused: false })
      }
      return { downloads: updated }
    })

    window.api.startDownload(download.originalRequest).catch((err) => {
      const errorMsg = cleanErrorMessage(err)
      set((s) => {
        const updated = new Map(s.downloads)
        const existing = updated.get(id)
        if (existing) {
          updated.set(id, { ...existing, status: 'error', error: errorMsg })
        }
        return { downloads: updated }
      })
    })
  },

  pauseAll: () => {
    const state = get()
    for (const [id, d] of state.downloads) {
      if (d.status === 'downloading' || d.status === 'queued' || d.status === 'merging' || d.status === 'transcoding') {
        get().pauseDownload(id)
      }
    }
  },

  resumeAll: async () => {
    const state = get()
    const paused = Array.from(state.downloads.values()).filter((d) => d.paused)
    for (const d of paused) {
      await get().resumeDownload(d.id)
    }
  },

  cancelAll: () => {
    const state = get()
    const updated = new Map(state.downloads)
    for (const [id, d] of state.downloads) {
      if (d.status === 'downloading' || d.status === 'queued' || d.status === 'merging' || d.status === 'transcoding' || d.status === 'paused') {
        window.api.cancelDownload(id)
        updated.set(id, { ...d, status: 'cancelled', speed: '', eta: '' })
      }
    }
    set({ downloads: updated })
  },

  retryFailed: async () => {
    const state = get()
    const failed = Array.from(state.downloads.values()).filter((d) => d.status === 'error')
    for (const d of failed) {
      if (d.originalRequest) {
        await get().retryDownload(d.id)
      }
    }
  },

  clearCompleted: () => {
    set((state) => {
      const updated = new Map(state.downloads)
      for (const [id, d] of state.downloads) {
        if (d.status === 'complete' || d.status === 'cancelled' || d.status === 'error') {
          updated.delete(id)
        }
      }
      return { downloads: updated }
    })
  },

  setDownloadDir: (dir) => set({ downloadDir: dir }),
  setSubtitleFormat: (fmt) => set({ subtitleFormat: fmt }),
  setCookieBrowser: (browser) => set({ cookieBrowser: browser }),
  setPreferredContainer: (fmt) => set({ preferredContainer: fmt }),
  setAudioConvertFormat: (fmt) => set({ audioConvertFormat: fmt }),
  setVideoTranscodeFormat: (fmt) => set({ videoTranscodeFormat: fmt }),
  setAutoIncludeAudioWithProfessionalTranscodes: (enabled) => set({ autoIncludeAudioWithProfessionalTranscodes: enabled }),
  setFfmpegAvailable: (available) => set({ ffmpegAvailable: available }),
  setHwAccel: (hw) => set({ hwAccel: hw }),
  setAnalyticsEnabled: (enabled) => set({ analyticsEnabled: enabled }),
  setOrganizeIntoFolders: (v) => set({ organizeIntoFolders: v }),
  setDownloadAllInclude: (key, value) =>
    set((state) => ({
      downloadAllIncludes: { ...state.downloadAllIncludes, [key]: value }
    })),
  setActiveTab: (tab) =>
    set((state) => updateActiveTab(state, () => ({ activeTab: tab }))),

  reset: () =>
    set((state) =>
      updateActiveTab(state, () => ({
        mode: 'url',
        url: '',
        isLoading: false,
        error: null,
        videoInfo: null,
        playlistEntries: null,
        playlistMetadata: null,
        selectedFormats: new Set<string>(),
        selectedSubtitles: new Set<string>(),
        selectedExtras: new Set<string>(),
        activeTab: 'formats'
      }))
    ),

  restorePersistedState: (persisted) => {
    const s = persisted.settings as Record<string, unknown>
    const updates: Partial<AppState> = {}

    if (s.downloadDir && typeof s.downloadDir === 'string') updates.downloadDir = s.downloadDir
    if (s.subtitleFormat) updates.subtitleFormat = s.subtitleFormat as AppState['subtitleFormat']
    if (s.cookieBrowser) updates.cookieBrowser = s.cookieBrowser as AppState['cookieBrowser']
    if (s.preferredContainer) updates.preferredContainer = s.preferredContainer as AppState['preferredContainer']
    if (s.audioConvertFormat) updates.audioConvertFormat = s.audioConvertFormat as AppState['audioConvertFormat']
    if (s.videoTranscodeFormat) updates.videoTranscodeFormat = s.videoTranscodeFormat as AppState['videoTranscodeFormat']
    if (typeof s.autoIncludeAudioWithProfessionalTranscodes === 'boolean') {
      updates.autoIncludeAudioWithProfessionalTranscodes = s.autoIncludeAudioWithProfessionalTranscodes
    }
    if (s.hwAccel) updates.hwAccel = s.hwAccel as AppState['hwAccel']
    if (typeof s.analyticsEnabled === 'boolean') updates.analyticsEnabled = s.analyticsEnabled
    if (typeof s.organizeIntoFolders === 'boolean') updates.organizeIntoFolders = s.organizeIntoFolders
    if (s.downloadAllIncludes && typeof s.downloadAllIncludes === 'object') {
      updates.downloadAllIncludes = s.downloadAllIncludes as AppState['downloadAllIncludes']
    }

    const tabUrls = persisted.tabUrls?.filter((u: string) => u.trim()) ?? []
    if (tabUrls.length > 0) {
      const restoredTabs = tabUrls.map((url: string) => ({
        ...createTab(),
        mode: 'url' as const,
        url
      }))
      updates.tabs = restoredTabs as AppState['tabs']
      updates.activeTabId = restoredTabs[0].id
    }

    set(updates)
  },

  totalSelectedCount: () => {
    const state = get()
    const tab = _getActiveTab(state)
    if (!tab) return 0
    return tab.selectedFormats.size + tab.selectedSubtitles.size + tab.selectedExtras.size
  },

  selectedActionSummary: () => {
    const state = get()
    const tab = _getActiveTab(state)
    const videoInfo = tab?.videoInfo
    let hasTranscode = false
    let hasConvert = false
    let hasMux = false

    if (tab && videoInfo) {
      const formatsById = new Map(videoInfo.formats.map((format) => [format.formatId, format]))
      for (const formatId of tab.selectedFormats) {
        if (formatId.startsWith('bestvideo[')) {
          const mergeKind = selectedMergePresetActionKind(formatId, videoInfo, state.preferredContainer)
          if (mergeKind === 'transcode') {
            hasTranscode = true
          } else {
            hasMux = true
          }
          continue
        }

        const format = formatsById.get(formatId)
        if (!format) continue
        if (selectedFormatNeedsTranscode(format, state.preferredContainer, state.videoTranscodeFormat)) {
          hasTranscode = true
        }
        if (selectedFormatNeedsConvert(format, state.audioConvertFormat)) {
          hasConvert = true
        }
        if (selectedFormatNeedsMux(format)) {
          hasMux = true
        }
      }

      if (tab.selectedSubtitles.size > 0 && state.subtitleFormat !== 'original') {
        hasConvert = true
      }
    }

    const kind: SelectedActionKind = hasTranscode
      ? 'transcode'
      : hasConvert
        ? 'convert'
        : hasMux
          ? 'mux'
          : 'download'
    const label = kind === 'transcode'
      ? 'Transcode + Download'
      : kind === 'convert'
        ? 'Convert + Download'
        : kind === 'mux'
          ? 'Mux + Download'
          : 'Download'

    return { kind, label, hasTranscode, hasConvert, hasMux }
  },

  estimatedTotalSize: () => {
    const state = get()
    const tab = _getActiveTab(state)
    if (!tab?.videoInfo) return null

    const info = tab.videoInfo
    let total = 0
    let hasEstimate = false

    for (const formatId of tab.selectedFormats) {
      if (formatId.startsWith('bestvideo[')) {
        const resMatch = formatId.match(/height<=(\d+)/)
        if (resMatch) {
          const res = parseInt(resMatch[1])
          const bestVideo = info.formats
            .filter((f) => f.type === 'video-only' && (f.height ?? 0) <= res)
            .sort((a, b) => (b.height ?? 0) - (a.height ?? 0))[0]
          const bestAudio = info.formats
            .filter((f) => f.type === 'audio-only')
            .sort((a, b) => (b.abr ?? b.tbr ?? 0) - (a.abr ?? a.tbr ?? 0))[0]
          const vSize = bestVideo?.filesize ?? bestVideo?.filesizeApprox ?? null
          const aSize = bestAudio?.filesize ?? bestAudio?.filesizeApprox ?? null
          if (vSize) { total += vSize; hasEstimate = true }
          if (aSize) { total += aSize }
        }
        continue
      }

      const format = info.formats.find((f) => f.formatId === formatId)
      if (format) {
        const size =
          format.filesize ??
          format.filesizeApprox ??
          (format.tbr && info.duration ? (format.tbr * 1000 / 8) * info.duration : null)
        if (size) {
          total += size
          hasEstimate = true
        }
      }
    }

    return hasEstimate ? total : null
  }
}))

export function useActiveTab(): TabState | undefined {
  return useAppStore((s) => s.tabs.find((t) => t.id === s.activeTabId))
}
