import type { ElectronAPI } from '@electron-toolkit/preload'

export interface YtdlpFormat {
  formatId: string
  ext: string
  resolution: string | null
  width: number | null
  height: number | null
  fps: number | null
  vcodec: string | null
  acodec: string | null
  filesize: number | null
  filesizeApprox: number | null
  tbr: number | null
  abr: number | null
  vbr: number | null
  formatNote: string
  type: 'combined' | 'video-only' | 'audio-only'
  container: string | null
  dynamicRange: string | null
  sampleRate: number | null
  audioChannels: number | null
}

export interface SubtitleTrack {
  language: string
  languageName: string
  ext: string
  url: string
  isAutoGenerated: boolean
}

export interface ThumbnailInfo {
  id: string
  url: string
  width: number | null
  height: number | null
  resolution: string
}

export interface ChapterInfo {
  title: string
  startTime: number
  endTime: number
}

export interface VideoInfo {
  id: string
  title: string
  thumbnail: string
  duration: number
  uploader: string
  uploaderUrl: string | null
  viewCount: number | null
  likeCount: number | null
  uploadDate: string | null
  description: string | null
  tags: string[]
  categories: string[]
  formats: YtdlpFormat[]
  subtitles: Record<string, SubtitleTrack[]>
  automaticCaptions: Record<string, SubtitleTrack[]>
  thumbnails: ThumbnailInfo[]
  chapters: ChapterInfo[]
  isPlaylist: boolean
  playlistTitle?: string
  playlistCount?: number
}

export interface PlaylistEntry {
  id: string
  title: string
  url: string
  duration: number | null
  thumbnail: string | null
}

export interface PlaylistMetadata {
  title: string | null
  channelName: string | null
  playlistName: string | null
  count: number | null
}

export interface PlaylistFetchResult {
  entries: PlaylistEntry[]
  metadata: PlaylistMetadata
}

export interface UrlPreview {
  title: string | null
}

export type CookieBrowser = 'none' | 'chrome' | 'firefox' | 'safari' | 'edge' | 'brave' | 'zen' | 'helium'

export type BrowserSignInStatusCode = 'off' | 'ready' | 'not-found' | 'browser-open' | 'permission-denied' | 'error'

export interface BrowserSignInStatus {
  browser: CookieBrowser
  status: BrowserSignInStatusCode
  message: string
}

export interface DownloadRequest {
  id: string
  url: string
  type: 'format' | 'subtitle' | 'auto-subtitle' | 'thumbnail' | 'description' | 'info-json' | 'comments'
  formatId?: string
  subtitleLang?: string
  subtitleSourceFormat?: string
  subtitleFormat?: string
  outputDir: string
  filename?: string
  cookieBrowser?: CookieBrowser
  audioConvertTo?: 'wav' | 'flac' | 'mp3'
  videoTranscodeTo?: 'h264-mp4' | 'prores' | 'dnxhr'
  includeBestAudio?: boolean
  videoDuration?: number
  videoTitle?: string
}

export interface DownloadProgress {
  id: string
  percent: number
  speed: string
  eta: string
  stage: 'downloading' | 'merging' | 'postprocessing' | 'complete' | 'error'
  filename?: string
  totalSize?: string
}

export interface DownloadComplete {
  id: string
  filePath: string
  fileSize: number
}

export interface DownloadError {
  id: string
  error: string
}

export interface BinaryStatus {
  ytdlpPath: string | null
  ytdlpVersion: string | null
  ytdlpSource: 'user' | 'bundled' | 'system' | null
  ytdlpLatestVersion: string | null
  ytdlpUpdateAvailable: boolean
  ffmpegPath: string | null
  ffmpegVersion: string | null
  ffmpegSource: 'user' | 'bundled' | 'system' | null
  ffmpegLatestVersion: string | null
  ffmpegUpdateAvailable: boolean
}

export interface AppUpdateStatus {
  state: 'checking' | 'available' | 'not-available' | 'downloading' | 'downloaded' | 'error'
  version?: string
  releaseNotes?: string
  message?: string
  percent?: number
  bytesPerSecond?: number
  transferred?: number
  total?: number
}

export interface LicenseState {
  isOfficialBuild: boolean
  trialStartedAt: string
  trialEndsAt: string
  trialDaysRemaining: number
  isTrialExpired: boolean
  trialStatus: 'active' | 'expired' | 'converted' | 'voided'
  trialSource: 'local' | 'backend'
  isActivated: boolean
  entitlement: {
    licenseId: string
    activationId: string
    plan: 'solo' | 'personal' | 'extended' | 'custom'
    features: string[]
    updatePolicy: 'lifetime'
    maxActivations: number
    issuedAt: string
  } | null
}

export type AppTelemetryEventName =
  | 'app.launched'
  | 'license.activation.started'
  | 'license.activation.succeeded'
  | 'license.activation.failed'
  | 'license.deactivation.succeeded'
  | 'license.recovery.started'
  | 'license.recovery.succeeded'
  | 'license.recovery.failed'
  | 'download.started'
  | 'download.succeeded'
  | 'download.failed'
  | 'update.check.started'
  | 'update.check.succeeded'
  | 'update.check.failed'
  | 'update.download.started'
  | 'update.download.succeeded'
  | 'update.download.failed'
  | 'feedback.opened'
  | 'feedback.submitted'

export type AppShortcutCommand =
  | 'open-settings'
  | 'new-tab'
  | 'reopen-closed-tab'
  | 'close-tab'
  | 'reload-tab'
  | 'focus-url'
  | `switch-tab:${number}`

export interface ElectronAppAPI {
  fetchVideoInfo(url: string, cookieBrowser?: CookieBrowser): Promise<VideoInfo>
  fetchPlaylist(url: string, cookieBrowser?: CookieBrowser): Promise<PlaylistFetchResult>
  fetchUrlPreview(url: string, cookieBrowser?: CookieBrowser): Promise<UrlPreview>
  checkBrowserSignIn(browser: CookieBrowser): Promise<BrowserSignInStatus>
  startDownload(request: DownloadRequest): Promise<string>
  cancelDownload(id: string): Promise<void>
  selectDirectory(): Promise<string | null>
  getBinaryStatus(includeLatest?: boolean): Promise<BinaryStatus>
  getAppVersion(): Promise<string>
  getLicenseState(): Promise<LicenseState>
  activateLicense(licenseKey: string): Promise<LicenseState>
  deactivateLicense(): Promise<LicenseState>
  checkForUpdates(): Promise<{ status: 'available' | 'not-available'; version?: string }>
  downloadAppUpdate(): Promise<void>
  installAppUpdate(): Promise<void>
  updateYtdlp(): Promise<string>
  downloadFfmpeg(): Promise<string>
  updateFfmpeg(): Promise<string>
  useBundledYtdlp(): Promise<BinaryStatus>
  useBundledFfmpeg(): Promise<BinaryStatus>
  openFile(path: string): Promise<void>
  revealInFolder(path: string): Promise<void>
  fileExists(path: string): Promise<boolean>
  openExternal(url: string): Promise<void>
  openFullDiskAccessSettings(): Promise<void>
  getDefaultDownloadDir(): Promise<string>
  loadPersistedState(): Promise<{ settings: Record<string, unknown>; tabUrls: string[] }>
  savePersistedState(state: { settings: Record<string, unknown>; tabUrls: string[] }): Promise<void>
  trackEvent(input: { eventType: AppTelemetryEventName; properties?: Record<string, unknown> }): Promise<{ recorded: boolean }>
  submitFeedback(input: {
    category: 'general' | 'bug' | 'feature' | 'license' | 'download' | 'update'
    message: string
    email?: string | null
    diagnostics?: Record<string, unknown>
  }): Promise<{ received: true }>
  exportChapters(opts: {
    chapters: { title: string; startTime: number; endTime: number }[]
    title: string
    format: 'premiere-csv' | 'edl' | 'csv' | 'txt'
    outputDir: string
    fps?: number
  }): Promise<{ filePath: string; fileSize: number }>
  loadDownloadHistory(): Promise<unknown[]>
  saveDownloadHistory(history: unknown[]): Promise<void>
  downloadThumbnail(opts: { url: string; outputDir: string; filename: string }): Promise<{ filePath: string; fileSize: number }>
  onDownloadProgress(callback: (progress: DownloadProgress) => void): () => void
  onDownloadComplete(callback: (result: DownloadComplete) => void): () => void
  onDownloadError(callback: (error: DownloadError) => void): () => void

  onAppUpdateStatus(callback: (status: AppUpdateStatus) => void): () => void
  onAppShortcut(callback: (command: AppShortcutCommand) => void): () => void
  platform: string
}

declare global {
  interface Window {
    api: ElectronAppAPI
    electron: ElectronAPI
  }
}
