import { useState, useMemo } from 'react'
import { useAppStore, useActiveTab } from '../stores/app-store'
import { getLanguageName } from '../lib/format-utils'
import type { SubtitleTrack } from '../types'

const LANGUAGE_FLAGS: Record<string, string> = {
  en: '\uD83C\uDDFA\uD83C\uDDF8', es: '\uD83C\uDDEA\uD83C\uDDF8', fr: '\uD83C\uDDEB\uD83C\uDDF7', de: '\uD83C\uDDE9\uD83C\uDDEA',
  it: '\uD83C\uDDEE\uD83C\uDDF9', pt: '\uD83C\uDDE7\uD83C\uDDF7', ru: '\uD83C\uDDF7\uD83C\uDDFA', ja: '\uD83C\uDDEF\uD83C\uDDF5',
  ko: '\uD83C\uDDF0\uD83C\uDDF7', zh: '\uD83C\uDDE8\uD83C\uDDF3', 'zh-Hans': '\uD83C\uDDE8\uD83C\uDDF3', 'zh-Hant': '\uD83C\uDDF9\uD83C\uDDFC',
  ar: '\uD83C\uDDF8\uD83C\uDDE6', hi: '\uD83C\uDDEE\uD83C\uDDF3', nl: '\uD83C\uDDF3\uD83C\uDDF1', pl: '\uD83C\uDDF5\uD83C\uDDF1',
  tr: '\uD83C\uDDF9\uD83C\uDDF7', sv: '\uD83C\uDDF8\uD83C\uDDEA', da: '\uD83C\uDDE9\uD83C\uDDF0', no: '\uD83C\uDDF3\uD83C\uDDF4',
  fi: '\uD83C\uDDEB\uD83C\uDDEE', uk: '\uD83C\uDDFA\uD83C\uDDE6', cs: '\uD83C\uDDE8\uD83C\uDDFF', el: '\uD83C\uDDEC\uD83C\uDDF7',
  he: '\uD83C\uDDEE\uD83C\uDDF1', th: '\uD83C\uDDF9\uD83C\uDDED', vi: '\uD83C\uDDFB\uD83C\uDDF3', id: '\uD83C\uDDEE\uD83C\uDDE9',
  ms: '\uD83C\uDDF2\uD83C\uDDFE', ro: '\uD83C\uDDF7\uD83C\uDDF4', hu: '\uD83C\uDDED\uD83C\uDDFA', bg: '\uD83C\uDDE7\uD83C\uDDEC',
  hr: '\uD83C\uDDED\uD83C\uDDF7', sk: '\uD83C\uDDF8\uD83C\uDDF0', sr: '\uD83C\uDDF7\uD83C\uDDF8', fil: '\uD83C\uDDF5\uD83C\uDDED',
  tl: '\uD83C\uDDF5\uD83C\uDDED', sw: '\uD83C\uDDF0\uD83C\uDDEA', ta: '\uD83C\uDDEE\uD83C\uDDF3', te: '\uD83C\uDDEE\uD83C\uDDF3',
  bn: '\uD83C\uDDE7\uD83C\uDDE9', ur: '\uD83C\uDDF5\uD83C\uDDF0', fa: '\uD83C\uDDEE\uD83C\uDDF7'
}

interface SubtitleRow {
  key: string
  language: string
  languageName: string
  ext: string
  isAutoGenerated: boolean
}

export function SubtitleList() {
  const tab = useActiveTab()
  const toggleSubtitle = useAppStore((s) => s.toggleSubtitle)
  const selectAllSubtitles = useAppStore((s) => s.selectAllSubtitles)
  const deselectAllSubtitles = useAppStore((s) => s.deselectAllSubtitles)
  const subtitleFormat = useAppStore((s) => s.subtitleFormat)
  const setSubtitleFormat = useAppStore((s) => s.setSubtitleFormat)

  const videoInfo = tab?.videoInfo ?? null
  const selectedSubtitles = tab?.selectedSubtitles ?? new Set<string>()

  const [filter, setFilter] = useState('')

  const { manualRows, autoRows } = useMemo(() => {
    if (!videoInfo) return { manualRows: [], autoRows: [] }

    const buildRows = (
      tracks: Record<string, SubtitleTrack[]>,
      isAuto: boolean
    ): SubtitleRow[] => {
      const rows: SubtitleRow[] = []
      for (const [lang, entries] of Object.entries(tracks)) {
        for (const track of entries) {
          if (track.isAutoGenerated === isAuto) {
            rows.push({
              key: `${lang}:${track.ext}`,
              language: lang,
              languageName: track.languageName || getLanguageName(lang),
              ext: track.ext,
              isAutoGenerated: isAuto
            })
          }
        }
      }
      // Deduplicate by language (keep first entry per language)
      const seen = new Set<string>()
      return rows.filter((r) => {
        if (seen.has(r.language)) return false
        seen.add(r.language)
        return true
      })
    }

    return {
      manualRows: buildRows(videoInfo.subtitles, false),
      autoRows: buildRows(videoInfo.automaticCaptions, true)
    }
  }, [videoInfo])

  const filterLower = filter.toLowerCase()
  const filteredManual = manualRows.filter(
    (r) =>
      r.languageName.toLowerCase().includes(filterLower) ||
      r.language.toLowerCase().includes(filterLower)
  )
  const filteredAuto = autoRows.filter(
    (r) =>
      r.languageName.toLowerCase().includes(filterLower) ||
      r.language.toLowerCase().includes(filterLower)
  )

  if (!videoInfo) return <></>

  return (
    <div className="space-y-4 animate-fade-in">
      <div className="glass rounded-xl px-4 py-3">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h3 className="text-sm font-medium text-surface-200">Subtitle output</h3>
            <p className="mt-0.5 text-xs text-surface-500">Keep the original source format or convert sources like json3 to an editor-friendly subtitle file.</p>
          </div>
          <div className="flex gap-2">
            {(['original', 'srt', 'vtt', 'ass'] as const).map((fmt) => (
              <button
                key={fmt}
                onClick={() => setSubtitleFormat(fmt)}
                className={`min-w-16 rounded-lg border px-3 py-1.5 text-xs font-medium transition-all duration-200 ${
                  subtitleFormat === fmt
                    ? 'border-accent-500/40 bg-accent-500/20 text-accent-300'
                    : 'border-surface-700/40 bg-surface-800/60 text-surface-400 hover:border-surface-600/50 hover:text-surface-200'
                }`}
              >
                {fmt === 'original' ? 'Original' : `.${fmt}`}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Search filter */}
      <div className="relative">
        <svg
          className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-surface-500"
          fill="none"
          viewBox="0 0 24 24"
          strokeWidth={1.5}
          stroke="currentColor"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z"
          />
        </svg>
        <input
          type="text"
          value={filter}
          onChange={(e) => setFilter(e.target.value)}
          placeholder="Filter by language..."
          className="input-field w-full pl-10 py-2.5 text-sm rounded-xl"
        />
      </div>

      {/* Manual Subtitles */}
      <SubtitleSection
        title="Manual Subtitles"
        rows={filteredManual}
        badgeColor="success"
        badgeLabel="Manual"
        selectedSubtitles={selectedSubtitles}
        subtitleFormat={subtitleFormat}
        onToggle={toggleSubtitle}
        onSelectAll={() => selectAllSubtitles(false)}
        onDeselectAll={() => deselectAllSubtitles(false)}
        emptyMessage="No manual subtitles available"
      />

      {/* Auto-Generated */}
      <SubtitleSection
        title="Auto-Generated"
        rows={filteredAuto}
        badgeColor="warning"
        badgeLabel="Auto"
        selectedSubtitles={selectedSubtitles}
        subtitleFormat={subtitleFormat}
        onToggle={toggleSubtitle}
        onSelectAll={() => selectAllSubtitles(true)}
        onDeselectAll={() => deselectAllSubtitles(true)}
        emptyMessage="No auto-generated subtitles available"
        disclaimer="Auto-generated subtitles may contain inaccuracies"
      />
    </div>
  )
}

interface SubtitleSectionProps {
  title: string
  rows: SubtitleRow[]
  badgeColor: 'success' | 'warning'
  badgeLabel: string
  selectedSubtitles: Set<string>
  subtitleFormat: string
  onToggle: (key: string) => void
  onSelectAll: () => void
  onDeselectAll: () => void
  emptyMessage: string
  disclaimer?: string
}

function SubtitleSection({
  title,
  rows,
  badgeColor,
  badgeLabel,
  selectedSubtitles,
  subtitleFormat,
  onToggle,
  onSelectAll,
  onDeselectAll,
  emptyMessage,
  disclaimer
}: SubtitleSectionProps) {
  const allSelected = rows.length > 0 && rows.every((r) => selectedSubtitles.has(r.key))
  const someSelected = rows.some((r) => selectedSubtitles.has(r.key))

  const badgeClasses =
    badgeColor === 'success'
      ? 'bg-success/15 text-success'
      : 'bg-warning/15 text-warning'

  return (
    <div className="glass rounded-xl overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 bg-surface-800/30">
        <div className="flex items-center gap-2">
          <h3 className="text-sm font-medium text-surface-200">{title}</h3>
          <span className="text-xs text-surface-500">({rows.length})</span>
        </div>
        {rows.length > 0 && (
          <button
            onClick={allSelected || someSelected ? onDeselectAll : onSelectAll}
            className="text-xs text-accent-400 hover:text-accent-300 font-medium transition-colors"
          >
            {allSelected || someSelected ? 'Deselect All' : 'Select All'}
          </button>
        )}
      </div>

      {/* Disclaimer */}
      {disclaimer && rows.length > 0 && (
        <div className="px-4 py-2 bg-warning/5 border-b border-warning/10 flex items-center gap-2">
          <svg className="w-3.5 h-3.5 text-warning shrink-0" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
          </svg>
          <span className="text-[11px] text-warning/80">{disclaimer}</span>
        </div>
      )}

      {/* Rows */}
      {rows.length === 0 ? (
        <div className="px-4 py-6 text-center">
          <p className="text-sm text-surface-500">{emptyMessage}</p>
        </div>
      ) : (
        <div className="divide-y divide-surface-800/40">
          {rows.map((row) => {
            const isSelected = selectedSubtitles.has(row.key)
            const flag = LANGUAGE_FLAGS[row.language] ?? LANGUAGE_FLAGS[row.language.split('-')[0]] ?? ''

            return (
              <button
                key={row.key}
                onClick={() => onToggle(row.key)}
                className={`w-full flex items-center gap-3 px-4 py-2.5 text-left transition-all duration-150 glass-hover ${
                  isSelected ? 'bg-accent-500/5 border-l-2 border-l-accent-500' : 'border-l-2 border-l-transparent'
                }`}
              >
                {/* Checkbox */}
                <div
                  className={`w-4 h-4 rounded border flex items-center justify-center shrink-0 transition-all duration-150 ${
                    isSelected
                      ? 'bg-accent-500 border-accent-500'
                      : 'border-surface-600 bg-surface-900/50'
                  }`}
                >
                  {isSelected && (
                    <svg className="w-3 h-3 text-white" fill="none" viewBox="0 0 24 24" strokeWidth={3} stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
                    </svg>
                  )}
                </div>

                {/* Flag */}
                {flag && <span className="text-sm shrink-0">{flag}</span>}

                {/* Language name + code */}
                <span className="text-sm text-surface-100 flex-1">
                  {row.languageName}
                  <span className="text-surface-500 ml-1.5">({row.language})</span>
                </span>

                {/* Type badge */}
                <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full shrink-0 ${badgeClasses}`}>
                  {badgeLabel}
                </span>

                {/* Format indicator */}
                <span className="text-[10px] font-mono text-surface-400 bg-surface-800/60 px-2 py-0.5 rounded shrink-0">
                  {subtitleFormat === 'original' || row.ext === subtitleFormat ? row.ext : `${row.ext} → ${subtitleFormat}`}
                </span>
              </button>
            )
          })}
        </div>
      )}
    </div>
  )
}
