import { execFile } from 'child_process'
import {
  browserLabel,
  browserProcessName,
  checkCookieBrowserReadiness,
  resolveCookieBrowserArgument
} from './browser-cookies'
import type {
  VideoInfo,
  YtdlpFormat,
  SubtitleTrack,
  ThumbnailInfo,
  ChapterInfo,
  PlaylistEntry,
  PlaylistFetchResult,
  PlaylistMetadata,
  BrowserSignInStatus,
  CookieBrowser
} from './types'

interface YtdlpRawFormat {
  format_id: string
  ext: string
  resolution?: string
  width?: number | null
  height?: number | null
  fps?: number | null
  vcodec?: string | null
  acodec?: string | null
  filesize?: number | null
  filesize_approx?: number | null
  tbr?: number | null
  abr?: number | null
  vbr?: number | null
  format_note?: string
  container?: string | null
  dynamic_range?: string | null
  asr?: number | null
  audio_channels?: number | null
}

interface YtdlpRawSubtitle {
  ext: string
  url: string
  name?: string
}

interface YtdlpRawThumbnail {
  id?: string
  url: string
  width?: number | null
  height?: number | null
  resolution?: string
}

interface YtdlpRawChapter {
  title?: string
  start_time: number
  end_time: number
}

interface YtdlpRawJson {
  id: string
  title: string
  thumbnail?: string
  duration?: number
  uploader?: string
  uploader_url?: string | null
  view_count?: number | null
  like_count?: number | null
  upload_date?: string | null
  description?: string | null
  tags?: string[] | null
  categories?: string[] | null
  formats?: YtdlpRawFormat[]
  subtitles?: Record<string, YtdlpRawSubtitle[]>
  automatic_captions?: Record<string, YtdlpRawSubtitle[]>
  thumbnails?: YtdlpRawThumbnail[]
  chapters?: YtdlpRawChapter[] | null
  playlist_title?: string | null
  playlist_count?: number | null
  channel?: string | null
  channel_id?: string | null
  uploader_id?: string | null
  playlist?: string | null
  playlist_uploader?: string | null
  playlist_uploader_id?: string | null
  entries?: YtdlpRawPlaylistEntry[]
  _type?: string
}

interface YtdlpRawPlaylistEntry {
  id: string
  title?: string
  url: string
  duration?: number | null
  thumbnail?: string | null
  thumbnails?: Array<{ url?: string | null }>
}

function classifyFormatType(raw: YtdlpRawFormat): YtdlpFormat['type'] {
  const hasVideo = raw.vcodec != null && raw.vcodec !== 'none'
  const hasAudio = raw.acodec != null && raw.acodec !== 'none'
  if (hasVideo && hasAudio) return 'combined'
  if (hasVideo) return 'video-only'
  return 'audio-only'
}

function mapFormat(raw: YtdlpRawFormat): YtdlpFormat {
  return {
    formatId: raw.format_id,
    ext: raw.ext,
    resolution: raw.resolution ?? null,
    width: raw.width ?? null,
    height: raw.height ?? null,
    fps: raw.fps ?? null,
    vcodec: raw.vcodec ?? null,
    acodec: raw.acodec ?? null,
    filesize: raw.filesize ?? null,
    filesizeApprox: raw.filesize_approx ?? null,
    tbr: raw.tbr ?? null,
    abr: raw.abr ?? null,
    vbr: raw.vbr ?? null,
    formatNote: raw.format_note ?? '',
    type: classifyFormatType(raw),
    container: raw.container ?? null,
    dynamicRange: raw.dynamic_range ?? null,
    sampleRate: raw.asr ?? null,
    audioChannels: raw.audio_channels ?? null
  }
}

/** Collapse HLS stream segment duplicates (e.g. format IDs 91-0, 91-1, ...) that
 *  share the same resolution, codec, and container. Keeps the highest bitrate variant. */
function deduplicateFormats(formats: YtdlpFormat[]): YtdlpFormat[] {
  const seen = new Map<string, YtdlpFormat>()
  const result: YtdlpFormat[] = []

  for (const f of formats) {
    // Only dedup combined formats — video-only and audio-only have meaningful differences
    if (f.type === 'combined') {
      const key = `${f.height ?? 0}_${f.width ?? 0}_${(f.vcodec ?? '').slice(0, 5)}_${(f.acodec ?? '').slice(0, 5)}_${f.ext}`
      const existing = seen.get(key)
      if (existing) {
        // Keep whichever has higher bitrate
        if ((f.tbr ?? 0) > (existing.tbr ?? 0)) {
          seen.set(key, f)
        }
        continue
      }
      seen.set(key, f)
    }
    result.push(f)
  }

  // Replace combined entries with the best-bitrate winners
  return result.map((f) => {
    if (f.type === 'combined') {
      const key = `${f.height ?? 0}_${f.width ?? 0}_${(f.vcodec ?? '').slice(0, 5)}_${(f.acodec ?? '').slice(0, 5)}_${f.ext}`
      return seen.get(key) ?? f
    }
    return f
  })
}

function mapSubtitles(
  raw: Record<string, YtdlpRawSubtitle[]> | undefined,
  isAutoGenerated: boolean,
  langNames?: Record<string, YtdlpRawSubtitle[]>
): Record<string, SubtitleTrack[]> {
  if (!raw) return {}
  const result: Record<string, SubtitleTrack[]> = {}
  for (const [lang, tracks] of Object.entries(raw)) {
    result[lang] = tracks.map((track) => ({
      language: lang,
      languageName: track.name ?? lang,
      ext: track.ext,
      url: track.url,
      isAutoGenerated
    }))
  }
  // Use langNames if provided for better language name resolution
  if (langNames) {
    for (const [lang, tracks] of Object.entries(langNames)) {
      if (result[lang] && tracks.length > 0 && tracks[0].name) {
        for (const sub of result[lang]) {
          sub.languageName = tracks[0].name
        }
      }
    }
  }
  return result
}

function mapThumbnails(raw: YtdlpRawThumbnail[] | undefined): ThumbnailInfo[] {
  if (!raw) return []
  return raw.map((t, index) => ({
    id: t.id ?? String(index),
    url: t.url,
    width: t.width ?? null,
    height: t.height ?? null,
    resolution: (() => {
      // Override yt-dlp's incorrect maxresdefault dimensions
      if (t.url.includes('maxresdefault') && t.width === 1920) return '1280x720'
      return t.resolution || (t.width && t.height ? `${t.width}x${t.height}` : guessThumbResolution(t.url))
    })()
  }))
}

function guessThumbResolution(url: string): string {
  // YouTube thumbnail URLs contain resolution hints
  // Note: maxresdefault is labeled 1920x1080 by yt-dlp but YouTube actually serves 1280x720 for most videos
  const filename = url.split('/').pop()?.split('?')[0] ?? ''
  if (filename.includes('maxresdefault')) return '1280x720'
  if (filename.includes('hq720')) return '1280x720'
  if (filename.includes('sddefault')) return '640x480'
  if (filename.startsWith('sd')) return '640x480'
  if (filename.includes('hqdefault')) return '480x360'
  if (filename.startsWith('hq')) return '480x360'
  if (filename.includes('mqdefault')) return '320x180'
  if (filename.startsWith('mq')) return '320x180'
  if (filename === 'default.jpg' || filename === 'default.webp') return '120x90'
  // Numeric thumbnails (0.jpg, 1.jpg, 2.jpg, 3.jpg) are 480x360 frame captures
  if (/^\d\.(jpg|webp|png)$/.test(filename)) return '480x360'
  return 'unknown'
}

function mapChapters(raw: YtdlpRawChapter[] | null | undefined): ChapterInfo[] {
  if (!raw) return []
  return raw.map((ch) => ({
    title: ch.title ?? 'Untitled',
    startTime: ch.start_time,
    endTime: ch.end_time
  }))
}

function extractErrorMessage(stderr: string): string {
  // Pull out the actual ERROR line(s) from yt-dlp stderr, ignoring WARNINGs
  const errorLines = stderr
    .split('\n')
    .filter((line) => line.includes('ERROR:'))
    .map((line) => line.replace(/^.*ERROR:\s*/, '').trim())

  if (errorLines.length > 0) return errorLines.join('. ')

  // Fallback: return last non-empty line
  const lines = stderr.trim().split('\n').filter(Boolean)
  return lines[lines.length - 1] ?? 'Unknown yt-dlp error'
}

function runYtdlp(ytdlpPath: string, args: string[], timeoutMs = 60000): Promise<string> {
  return new Promise((resolve, reject) => {
    execFile(ytdlpPath, args, { maxBuffer: 50 * 1024 * 1024, timeout: timeoutMs }, (error, stdout, stderr) => {
      if (error) {
        if (error.killed || error.signal === 'SIGTERM') {
          reject(new Error('yt-dlp timed out'))
          return
        }
        reject(new Error(extractErrorMessage(stderr || error.message)))
        return
      }
      resolve(stdout)
    })
  })
}

function isBrowserRunning(browser: CookieBrowser): Promise<boolean> {
  const processName = browserProcessName(browser)
  if (!processName) return Promise.resolve(false)

  return new Promise((resolve) => {
    execFile('/usr/bin/pgrep', ['-x', processName], { timeout: 2000 }, (error) => {
      resolve(!error)
    })
  })
}

export async function checkBrowserSignIn(browser: CookieBrowser, _ytdlpPath: string): Promise<BrowserSignInStatus> {
  if (browser === 'none') {
    return {
      browser,
      status: 'off',
      message: 'YouTube sign-in is off.'
    }
  }

  const label = browserLabel(browser)
  if (await isBrowserRunning(browser)) {
    return {
      browser,
      status: 'browser-open',
      message: `Fully quit ${label}, then check sign-in again.`
    }
  }

  return checkCookieBrowserReadiness(browser)
}

async function fetchOembedTitle(url: string): Promise<string | null> {
  const endpoint = new URL('https://www.youtube.com/oembed')
  endpoint.searchParams.set('url', url)
  endpoint.searchParams.set('format', 'json')

  const controller = new AbortController()
  const timeout = setTimeout(() => controller.abort(), 3000)
  try {
    const response = await fetch(endpoint, {
      signal: controller.signal,
      headers: { accept: 'application/json' }
    })
    if (!response.ok) return null

    const payload = await response.json() as { title?: unknown }
    return cleanDisplayText(typeof payload.title === 'string' ? payload.title : null)
  } catch {
    return null
  } finally {
    clearTimeout(timeout)
  }
}

export async function fetchVideoInfo(url: string, ytdlpPath: string, cookieBrowser?: CookieBrowser): Promise<VideoInfo> {
  const args = ['--dump-json', '--no-download']
  const cookieBrowserArgument = await resolveCookieBrowserArgument(cookieBrowser)
  if (cookieBrowserArgument) {
    args.push('--cookies-from-browser', cookieBrowserArgument)
  }
  args.push(url)
  const stdout = await runYtdlp(ytdlpPath, args)
  const raw: YtdlpRawJson = JSON.parse(stdout)

  return {
    id: raw.id,
    title: raw.title,
    thumbnail: raw.thumbnail ?? '',
    duration: raw.duration ?? 0,
    uploader: raw.uploader ?? 'Unknown',
    uploaderUrl: raw.uploader_url ?? null,
    viewCount: raw.view_count ?? null,
    likeCount: raw.like_count ?? null,
    uploadDate: raw.upload_date ?? null,
    description: raw.description ?? null,
    tags: raw.tags ?? [],
    categories: raw.categories ?? [],
    formats: deduplicateFormats((raw.formats ?? []).map(mapFormat)),
    subtitles: mapSubtitles(raw.subtitles, false),
    automaticCaptions: mapSubtitles(raw.automatic_captions, true),
    thumbnails: mapThumbnails(raw.thumbnails),
    chapters: mapChapters(raw.chapters),
    isPlaylist: raw._type === 'playlist' || raw.playlist_title != null,
    playlistTitle: raw.playlist_title ?? undefined,
    playlistCount: raw.playlist_count ?? undefined
  }
}

export async function fetchUrlPreview(url: string, ytdlpPath: string, cookieBrowser?: CookieBrowser): Promise<{ title: string | null }> {
  const oembedTitle = await fetchOembedTitle(url)
  if (oembedTitle) return { title: oembedTitle }

  const args = ['--flat-playlist', '--dump-single-json', '--playlist-end', '1']
  const cookieBrowserArgument = await resolveCookieBrowserArgument(cookieBrowser)
  if (cookieBrowserArgument) {
    args.push('--cookies-from-browser', cookieBrowserArgument)
  }
  args.push(url)

  const stdout = await runYtdlp(ytdlpPath, args, 15000)
  const raw: YtdlpRawJson = JSON.parse(stdout)
  const title = cleanDisplayText(raw.playlist_title ?? raw.playlist ?? raw.title)
  return { title }
}

export async function fetchPlaylistEntries(url: string, ytdlpPath: string, cookieBrowser?: CookieBrowser): Promise<PlaylistFetchResult> {
  const args = ['--flat-playlist', '--dump-single-json']
  const cookieBrowserArgument = await resolveCookieBrowserArgument(cookieBrowser)
  if (cookieBrowserArgument) {
    args.push('--cookies-from-browser', cookieBrowserArgument)
  }
  args.push(url)
  const stdout = await runYtdlp(ytdlpPath, args)
  const raw: YtdlpRawJson = JSON.parse(stdout)

  const entries = mapPlaylistEntries(raw.entries ?? [])

  return {
    entries: entries.length > 0
      ? entries
      : await fetchPlaylistEntryLines(url, ytdlpPath, cookieBrowser),
    metadata: derivePlaylistMetadata(raw, entries.length)
  }
}

async function fetchPlaylistEntryLines(url: string, ytdlpPath: string, cookieBrowser?: CookieBrowser): Promise<PlaylistEntry[]> {
  const args = ['--flat-playlist', '--dump-json']
  const cookieBrowserArgument = await resolveCookieBrowserArgument(cookieBrowser)
  if (cookieBrowserArgument) {
    args.push('--cookies-from-browser', cookieBrowserArgument)
  }
  args.push(url)
  const stdout = await runYtdlp(ytdlpPath, args)
  const entries: YtdlpRawPlaylistEntry[] = []
  for (const line of stdout.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed) continue
    entries.push(JSON.parse(trimmed))
  }
  return mapPlaylistEntries(entries)
}

function mapPlaylistEntries(rawEntries: YtdlpRawPlaylistEntry[]): PlaylistEntry[] {
  const entries: PlaylistEntry[] = []
  for (const entry of rawEntries) {
    if (!entry.id) continue
    // thumbnail field is null for flat-playlist; grab largest from thumbnails array
    let thumbnail = entry.thumbnail ?? null
    if (!thumbnail && Array.isArray(entry.thumbnails) && entry.thumbnails.length > 0) {
      thumbnail = entry.thumbnails[entry.thumbnails.length - 1].url ?? null
    }
    entries.push({
      id: entry.id,
      title: entry.title ?? 'Untitled',
      url: entry.url || `https://www.youtube.com/watch?v=${entry.id}`,
      duration: entry.duration ?? null,
      thumbnail
    })
  }
  return entries
}

function derivePlaylistMetadata(raw: YtdlpRawJson, entryCount: number): PlaylistMetadata {
  const playlistName = cleanDisplayText(raw.playlist_title ?? raw.playlist ?? raw.title)
  const channelName = cleanDisplayText(raw.channel ?? raw.playlist_uploader ?? raw.uploader)
  const count = typeof raw.playlist_count === 'number' && raw.playlist_count >= 0
    ? Math.floor(raw.playlist_count)
    : entryCount

  return {
    title: [channelName, playlistName].filter(Boolean).join(' / ') || playlistName || channelName || null,
    channelName: channelName,
    playlistName: playlistName,
    count
  }
}

function cleanDisplayText(value: string | null | undefined): string | null {
  const trimmed = value?.trim()
  return trimmed ? trimmed.slice(0, 160) : null
}

export function isPlaylistUrl(url: string): boolean {
  try {
    const parsed = new URL(url)
    if (parsed.searchParams.has('list')) return true
    if (parsed.pathname.includes('/playlist')) return true
    if (parsed.pathname.startsWith('/@') || parsed.pathname.includes('/channel/') || parsed.pathname.includes('/c/')) {
      return true
    }
    return false
  } catch {
    return false
  }
}
