export interface YtdlpFormat {
  formatId: string
  ext: string
  resolution: string | null
  width: number | null
  height: number | null
  fps: number | null
  vcodec: string | null
  acodec: string | null
  filesize: number | null
  filesizeApprox: number | null
  tbr: number | null
  abr: number | null
  vbr: number | null
  formatNote: string
  type: 'combined' | 'video-only' | 'audio-only'
  container: string | null
  dynamicRange: string | null
  sampleRate: number | null
  audioChannels: number | null
}

export interface SubtitleTrack {
  language: string
  languageName: string
  ext: string
  url: string
  isAutoGenerated: boolean
}

export interface ThumbnailInfo {
  id: string
  url: string
  width: number | null
  height: number | null
  resolution: string
}

export interface ChapterInfo {
  title: string
  startTime: number
  endTime: number
}

export interface VideoInfo {
  id: string
  title: string
  thumbnail: string
  duration: number
  uploader: string
  uploaderUrl: string | null
  viewCount: number | null
  likeCount: number | null
  uploadDate: string | null
  description: string | null
  tags: string[]
  categories: string[]
  formats: YtdlpFormat[]
  subtitles: Record<string, SubtitleTrack[]>
  automaticCaptions: Record<string, SubtitleTrack[]>
  thumbnails: ThumbnailInfo[]
  chapters: ChapterInfo[]
  isPlaylist: boolean
  playlistTitle?: string
  playlistCount?: number
}

export interface PlaylistEntry {
  id: string
  title: string
  url: string
  duration: number | null
  thumbnail: string | null
}

export interface PlaylistMetadata {
  title: string | null
  channelName: string | null
  playlistName: string | null
  count: number | null
}

export interface PlaylistFetchResult {
  entries: PlaylistEntry[]
  metadata: PlaylistMetadata
}

export interface DownloadRequest {
  id: string
  url: string
  type: 'format' | 'subtitle' | 'auto-subtitle' | 'thumbnail' | 'description' | 'info-json' | 'comments'
  formatId?: string
  subtitleLang?: string
  subtitleSourceFormat?: string
  subtitleFormat?: string
  outputDir: string
  filename?: string
  cookieBrowser?: CookieBrowser
  preferredContainer?: 'mp4' | 'mkv' | 'webm' | 'auto'
  audioConvertTo?: 'wav' | 'flac' | 'mp3'
  videoTranscodeTo?: 'h264-mp4' | 'prores' | 'dnxhr'
  includeBestAudio?: boolean
  videoDuration?: number // seconds, for ffmpeg transcode progress calculation
  hwAccel?: 'cpu' | 'videotoolbox'
  videoTitle?: string
}

export type CookieBrowser = 'none' | 'chrome' | 'firefox' | 'safari' | 'edge' | 'brave' | 'zen' | 'helium'

export type BrowserSignInStatusCode = 'off' | 'ready' | 'not-found' | 'browser-open' | 'permission-denied' | 'error'

export interface BrowserSignInStatus {
  browser: CookieBrowser
  status: BrowserSignInStatusCode
  message: string
}

export interface DownloadProgress {
  id: string
  percent: number
  speed: string
  eta: string
  stage: 'downloading' | 'merging' | 'postprocessing' | 'complete' | 'error'
  filename?: string
  totalSize?: string
}

export interface DownloadComplete {
  id: string
  filePath: string
  fileSize: number
}

export interface DownloadError {
  id: string
  error: string
}

export interface BinaryStatus {
  ytdlpPath: string | null
  ytdlpVersion: string | null
  ytdlpSource: 'user' | 'bundled' | 'system' | null
  ytdlpLatestVersion: string | null
  ytdlpUpdateAvailable: boolean
  ffmpegPath: string | null
  ffmpegVersion: string | null
  ffmpegSource: 'user' | 'bundled' | 'system' | null
  ffmpegLatestVersion: string | null
  ffmpegUpdateAvailable: boolean
}
